name: learnenglish
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^1.2.0
  flutter_bloc: ^5.0.0
  http: ^0.12.1
  dartz: ^0.9.1
  shared_preferences: ^0.5.7+3
  get_it: ^4.0.2
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
