import '../../features/quiz/data/models/language_model.dart';

const SERVER_FAILURE_MESSAGE = "Server has failed to fetch.";
const CACHE_FAILURE_MESSAGE = "Caching has gone wrong.";
const CONNECTION_FAILURE_MESSAGE = "You don't have an internet connection.";
const UNEXPECTED_FAILURE_MESSAGE = "Unexpected error.";
List<LanguageModel> languages = <LanguageModel>[
  LanguageModel(name: "Amharic", code: "am"),
  LanguageModel(name: "Arabic", code: "ar"),
  LanguageModel(name: "Basque", code: "eu"),
  LanguageModel(name: "Bengali", code: "bn"),
  LanguageModel(name: "English (UK)", code: "en-GB"),
  LanguageModel(name: "Portuguese (Brazil)", code: "pt-BR"),
  LanguageModel(name: "Bulgarian", code: "bg"),
  LanguageModel(name: "Catalan", code: "ca"),
  LanguageModel(name: "Cherokee", code: "chr"),
  LanguageModel(name: "Croatian", code: "hr"),
  LanguageModel(name: "Czech", code: "cs"),
  LanguageModel(name: "Danish", code: "da"),
  LanguageModel(name: "Dutch", code: "nl"),
  LanguageModel(name: "English (US)", code: "en"),
  LanguageModel(name: "Estonian", code: "et"),
  LanguageModel(name: "Filipino", code: "fil"),
  LanguageModel(name: "Finnish", code: "fi"),
  LanguageModel(name: "French", code: "fr"),
  LanguageModel(name: "German", code: "de"),
  LanguageModel(name: "Greek", code: "el"),
  LanguageModel(name: "Gujarati", code: "gu"),
  LanguageModel(name: "Hebrew", code: "iw"),
  LanguageModel(name: "Hindi", code: "hi"),
  LanguageModel(name: "Hungarian", code: "hu"),
  LanguageModel(name: "Icelandic", code: "is"),
  LanguageModel(name: "Indonesian", code: "id"),
  LanguageModel(name: "Italian", code: "it"),
  LanguageModel(name: "Japanese", code: "ja"),
  LanguageModel(name: "Kannada", code: "kn"),
  LanguageModel(name: "Korean", code: "ko"),
  LanguageModel(name: "Latvian", code: "lv"),
  LanguageModel(name: "Lithuanian", code: "lt"),
  LanguageModel(name: "Malay", code: "ms"),
  LanguageModel(name: "Malayalam", code: "ml"),
  LanguageModel(name: "Marathi", code: "mr"),
  LanguageModel(name: "Norwegian", code: "no"),
  LanguageModel(name: "Polish", code: "pl"),
  LanguageModel(name: "Portuguese (Portugal)", code: "pt-PT"),
  LanguageModel(name: "Romanian", code: "ro"),
  LanguageModel(name: "Russian", code: "ru"),
  LanguageModel(name: "Serbian", code: "sr"),
  LanguageModel(name: "Chinese (PRC)", code: "zh-CN"),
  LanguageModel(name: "Slovak", code: "sk"),
  LanguageModel(name: "Slovenian", code: "sl"),
  LanguageModel(name: "Spanish", code: "es"),
  LanguageModel(name: "Swahili", code: "sw"),
  LanguageModel(name: "Swedish", code: "sv"),
  LanguageModel(name: "Tamil", code: "ta"),
  LanguageModel(name: "Telugu", code: "te"),
  LanguageModel(name: "Thai", code: "th"),
  LanguageModel(name: "Chinese (Taiwan)", code: "zh-TW"),
  LanguageModel(name: "Turkish", code: "tr"),
  LanguageModel(name: "Urdu", code: "ur"),
  LanguageModel(name: "Ukrainian", code: "uk"),
  LanguageModel(name: "Vietnamese", code: "vi"),
  LanguageModel(name: "Welsh", code: "cy"),
];
